--- 
javascripts: 
- base: 
  - jrails
  - jquery.cycle.min
  - jquery.autocomplete.pack
  - application
  - subcategories
  - regions
stylesheets: 
- base:
  - default
  - base
  - jquery.autocomplete