--- 
javascripts: 
- base: 
  - jrails
  - jquery.cycle.min
  - jquery.autocomplete.pack
  - application
  - regions
  - jquery.NobleCount.min
  - jquery.curvycorners.packed
stylesheets: 
- base:
  - default
  - base
  - jquery.autocomplete
- base_michael:
  - base
  - michael-default
  - michael-base
  - jquery.autocomplete
  - users
