development: &non_production_settings
  site_url: http://localhost:3000
  site_name: Be Amazing(development)
  admin_email: admin@beamazing.co.nz
  rake: /opt/ruby-enterprise-1.8.6-20080810/bin/rake
  
test:
  <<: *non_production_settings
  
production:
#  site_url: http://www.beamazing.co.nz
  site_url: http://75.101.132.186:9000
  site_name: Be Amazing
  admin_email: cbonnet99@gmail.com
  rake: /opt/ruby-enterprise-1.8.6-20080810/bin/rake
