development: &non_production_settings
  site_host:
      default: localhost:3000
      nz: nz.localhost:3000
      au: au.localhost:3000
  site_protocol: http
  logged_site_protocol: http
  site_name: Be Amazing(development)
  admin_email: cbonnet99@gmail.com
  sav: cbonnet99@yahoo.fr
  cyrille: cbonnet99@yahoo.fr
  megan: norma2@eurekacoaching.co.nz
  
test:
    site_host:
        default: test.host
        nz: test.host
        au: test.host.com.au
    site_protocol: http
    logged_site_protocol: http
    site_name: Be Amazing(test)
    admin_email: cbonnet99@gmail.com
    sav: cbonnet99@yahoo.fr
    cyrille: cbonnet99@yahoo.fr
    megan: norma2@eurekacoaching.co.nz
  
production:
  site_host: 
      default: www.zingabeam.com
      nz: nz.zingabeam.com
      au: au.zingabeam.com
  site_protocol: http
  logged_site_protocol: https
  site_name: Be Amazing
  admin_email: admin@beamazing.co.nz
  sav: sav@elevatecoaching.co.nz
  cyrille: cbonnet99@gmail.com
  megan: megan@beamazing.co.nz
staging:
    site_host:
        default: staging.beamazing.co.nz
        nz: nz.staging.zingabeam.com
        au: au.staging.zingabeam.com
    site_protocol: http
    logged_site_protocol: http
    site_name: Be Amazing [STAGING]
    admin_email: admin@beamazing.co.nz
    sav: sav@elevatecoaching.co.nz
    cyrille: cbonnet99@gmail.com
    megan: megan@beamazing.co.nz
  
