development: &non_production_settings
  site_host: localhost:3000
  site_name: Be Amazing(development)
  admin_email: admin@beamazing.co.nz
  rake: /opt/ruby-enterprise-1.8.6-20080810/bin/rake
  
test:
  <<: *non_production_settings
  
production:
  site_host: beta.beamazing.co.nz
  site_name: Be Amazing
  admin_email: cbonnet99@gmail.com
  rake: /opt/ruby-enterprise-1.8.6-20080810/bin/rake
