development: &non_production_settings
  site_url: http://localhost:3000
  site_name: Be Amazing
  admin_email: cbonnet99@gmail.com
  
test:
  <<: *non_production_settings
  
production:
  site_url: http://www.beamazing.co.nz
  site_name: Be Amazing
  admin_email: cbonnet99@gmail.com
