development: &non_production_settings
  site_host: localhost:3000
  site_protocol: http
  logged_site_protocol: http
  site_name: Be Amazing(development)
  admin_email: cbonnet99@gmail.com
  rake: /opt/ruby-enterprise-1.8.6-20080810/bin/rake
  sav: cbonnet99@yahoo.fr
  cyrille: cbonnet99@yahoo.fr
  megan: norma2@eurekacoaching.co.nz
  
test:
    site_host: test.host
    site_protocol: http
    logged_site_protocol: http
    site_name: Be Amazing(test)
    admin_email: cbonnet99@gmail.com
    rake: /opt/ruby-enterprise-1.8.6-20080810/bin/rake
    sav: cbonnet99@yahoo.fr
    cyrille: cbonnet99@yahoo.fr
    megan: norma2@eurekacoaching.co.nz
  
production:
  site_host: www.beamazing.co.nz
  site_protocol: http
  logged_site_protocol: https
  site_name: Be Amazing
  admin_email: admin@beamazing.co.nz
  rake: /opt/ruby-enterprise-1.8.6-20080810/bin/rake
  sav: sav@elevatecoaching.co.nz
  cyrille: cbonnet99@gmail.com
  megan: megan@beamazing.co.nz
staging:
    site_host: staging.beamazing.co.nz
    site_protocol: http
    logged_site_protocol: http
    site_name: Be Amazing [STAGING]
    admin_email: admin@beamazing.co.nz
    rake: /usr/local/bin/rake
    sav: sav@elevatecoaching.co.nz
    cyrille: cbonnet99@gmail.com
    megan: megan@beamazing.co.nz
  
