development: &non_production_settings
  site_host: localhost:3000
  site_name: Be Amazing(development)
  admin_email: cbonnet99@gmail.com
  rake: /opt/ruby-enterprise-1.8.6-20080810/bin/rake
  norma: norma2@eurekacoaching.co.nz
  sav: cbonnet99@yahoo.fr
  cyrille: cbonnet99@yahoo.fr
  megan: norma2@eurekacoaching.co.nz
  
test:
  <<: *non_production_settings
  
production:
  site_host: beta.beamazing.co.nz
  site_name: Be Amazing
  admin_email: admin@beamazing.co.nz
  rake: /opt/ruby-enterprise-1.8.6-20080810/bin/rake
  norma: norma@eurekacoaching.co.nz
  sav: sav@elevatecoaching.co.nz
  cyrille: cbonnet99@gmail.com
  megan: megan@beamazing.co.nz
  
