production:
    customer_key: ZDYWYWY1ODG1ZTG0NGQ5ZTKYNGZMYM
    api_key: MDCYODC0ZMNJOTBJNDI1NZG0N2I0MZ
    xero_url: https://networktest.xero.com/api.xro/1.0
development:
    customer_key: ZDYWYWY1ODG1ZTG0NGQ5ZTKYNGZMYM
    api_key: MDCYODC0ZMNJOTBJNDI1NZG0N2I0MZ
    xero_url: https://networktest.xero.com/api.xro/1.0
test:
    customer_key: ZDYWYWY1ODG1ZTG0NGQ5ZTKYNGZMYM
    api_key: MDCYODC0ZMNJOTBJNDI1NZG0N2I0MZ
    xero_url: https://networktest.xero.com/api.xro/1.0
    