#!/bin/sh
export AWS_ACCESS_KEY_ID=09M23471K1QC4FPBN9R2
export AWS_SECRET_ACCESS_KEY=vMIWZ6w/0b8PAdQIj2nZMjJ9aijbgX1mdpWe/fRI

find ~/backups/* -type f -mtime +14 | xargs rm -Rf
/var/rails/be_amazing/current/script/s3sync/s3sync.rb --debug -r ~/backups/ backups.beamazing.co.nz:/ > ~/s3sync.log 2> ~/s3sync.log
